version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
    - dhach
  ignore:
    - dependency-name: ansible
      versions:
        - "> 2.9.7"
