---
language: python

services:
  - docker

env:
  global:
    - ROLE_NAME=acme-letsencrypt
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8

install:
  - python -m pip -q install -r test-requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
