---

- import_tasks: preflight.yml
- import_tasks: prepare.yml
- import_tasks: setup_letsencrypt.yml

- include_tasks: generate_key_and_csr.yml
  with_items: "{{ le_certificates }}"
  loop_control:
    loop_var: certificate_request

- name: Print remaining validity
  debug:
    msg: "Certificate is still valid for {{ le_challenge.cert_days }} days. No need to renew"
  when: not renewal_needed and not le_force_renew

- include_tasks: get_certificates.yml
  with_items: "{{ le_certificates }}"
  loop_control:
    loop_var: certificate_request
  when: renewal_needed or le_force_renew
