---

lint: |
  set -e
  yamllint -f parsable .
  ansible-lint

platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml

scenario:
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
