---

driver:
  name: docker

lint: |
  set -e
  yamllint -f parsable .
  ansible-lint -c .ansible-lint.yml

platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    environment:
      container: docker

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml

scenario:
  test_sequence:
    - lint
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
