---

- name: Prepare | install dependencies
  hosts: all
  become: true
  tasks:
    - name: install dependencies (RedHat based systems)
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: true
      when: ansible_os_family == "RedHat"
    - name: install dependencies(Debian based systems)
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"
  vars:
    packages:
      - openssl
